### ISSUE TITLE
参考 _data/authors.yml 格式, 补充下个人描述.

### ISSUE THREAD

**Issue by drmingdrmer** [openacid/openacid.github.io#1]
用来支持文章中的作者简介:
![image](https://user-images.githubusercontent.com/44069/52104659-8dbb8400-2626-11e9-8a9f-81096073addc.png)

格式酱:

```yaml

xp:
    name     : 张炎泼(xp)
    bio      : "正在学画画, 主业是码农"
    avatar   : "/assets/images/author/xp.jpg"
    location : 
    links    :
        - label: "个人博客"
          icon : "fas fa-fw fa-link"
          url  : "https://drmingdrmer.github.io/"
        - label: "微博"
          icon : "fas fa-fw fa-weibo"
          url  : "https://weibo.com/drdrxp"
        - label: "GitHub"
          icon : "fab fa-fw fa-github"
          url  : "https://github.com/drmingdrmer"
```

使用方法是在文章的开头加上作者名字:

```yaml
---
title:      "哄好面试官系列-1: 比较2个python dict(多级)是否相同"
author:     xp    <-- 介里
categories:
    - tech
    - algorithm

```
